spring.application.name=CoesDental
spring.datasource.url=jdbc:mysql://localhost:3306/consultorioCoesDental
spring.datasource.username=root
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=MnWW5aJBggnpJVBQE6UJ2v96jTbq+Cjz+Qp7Wb5WOOU=